twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/themes/default': default_theme
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/bootstrap_5_custom.html.twig'

when@test:
    twig:
        strict_variables: true
