security:
    providers:
        users_in_database:
            entity:
                class: App\Core\Entity\User
                property: email
        app_user_provider:
            entity:
                class: App\Core\Entity\User
                property: email
