vich_uploader:
    mappings:
        category_images:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
